/* MMMOC -- учебная операционная система
 * (c) 2003, Kolia Morev <kolia39@mail.ru>
 *
 * keymap.h: Скан-коды клавиатуры.
 */

#define SC_Escape                  1
#define SC_one                     2
#define SC_two                     3
#define SC_three                   4
#define SC_four                    5
#define SC_five                    6
#define SC_six                     7
#define SC_seven                   8
#define SC_eight                   9
#define SC_nine                   10
#define SC_zero                   11
#define SC_minus                  12
#define SC_equal                  13
#define SC_Delete                 14
#define SC_Tab                    15
#define SC_q                      16
#define SC_w                      17
#define SC_e                      18
#define SC_r                      19
#define SC_t                      20
#define SC_y                      21
#define SC_u                      22
#define SC_i                      23
#define SC_o                      24
#define SC_p                      25
#define SC_bracketleft            26
#define SC_bracketright           27
#define SC_Return                 28
#define SC_LControl               29
#define SC_a                      30
#define SC_s                      31
#define SC_d                      32
#define SC_f                      33
#define SC_g                      34
#define SC_h                      35
#define SC_j                      36
#define SC_k                      37
#define SC_l                      38
#define SC_semicolon              39
#define SC_apostrophe             40
#define SC_grave                  41
#define SC_LShift                 42
#define SC_backslash              43
#define SC_z                      44
#define SC_x                      45
#define SC_c                      46
#define SC_v                      47
#define SC_b                      48
#define SC_n                      49
#define SC_m                      50
#define SC_comma                  51
#define SC_period                 52
#define SC_slash                  53
#define SC_RShift                 54
#define SC_KP_Multiply            55
#define SC_Alt                    56
#define SC_space                  57
#define SC_Caps_Lock              58
#define SC_F1                     59
#define SC_F2                     60
#define SC_F3                     61
#define SC_F4                     62
#define SC_F5                     63
#define SC_F6                     64
#define SC_F7                     65
#define SC_F8                     66
#define SC_F9                     67
#define SC_F10                    68
#define SC_Num_Lock               69
#define SC_Scroll_Lock            70
#define SC_KP_7                   71
#define SC_KP_8                   72
#define SC_KP_9                   73
#define SC_KP_Subtract            74
#define SC_KP_4                   75
#define SC_KP_5                   76
#define SC_KP_6                   77
#define SC_KP_Add                 78
#define SC_KP_1                   79
#define SC_KP_2                   80
#define SC_KP_3                   81
#define SC_KP_0                   82
#define SC_KP_Period              83
#define SC_Last_Console           84

#define SC_less                   86
#define SC_F11                    87
#define SC_F12                    88

#define SC_KP_Enter               96
#define SC_RControl               97
#define SC_KP_Divide              98
#define SC_Control_backslash      99
#define SC_AltGr                 100
#define SC_Break                 101
#define SC_Find                  102
#define SC_Up                    103
#define SC_Prior                 104
#define SC_Left                  105
#define SC_Right                 106
#define SC_Select                107
#define SC_Down                  108
#define SC_Next                  109
#define SC_Insert                110
#define SC_Remove                111
#define SC_Macro                 112
#define SC_F13                   113
#define SC_F14                   114
#define SC_Help                  115
#define SC_Do                    116
#define SC_F17                   117
#define SC_KP_MinPlus            118
#define SC_Pause                 119
